### ISSUE TITLE
Errors in ch08?

### ISSUE THREAD

**Issue by victorhck** [iggredible/Learn-Vim#100]
Hello.

I was reading/translating the [Clearing a register](https://github.com/iggredible/Learn-Vim/blob/master/ch08_registers.md#clearing-a-register) section in ch08 and I found texts a bit confusing, don't know if really are errors or maybe my english fails! (sure it's last option!)

First:
> Technically, there is no need to clear any register because the next register you store under the same name will overwrite it.

Maybe _register_ should be _text_ ?

Second:
> Another alternative is to run the command :call setreg('a', '') where "a is the register a.

Says  _where "a is register a_, but where is the text "a in that sentence?

Please, if this is right, just close and ignore this issue!!

Greetings

**Comment by iggredible** [comment]
Good point. I reread it and made some changes.

For the first one, the sentence now reads:

"Technically, there is no need to clear any register because the next text that you store under the same register name will overwrite it."

This is clearer.

I also updated the second one:

"Another alternative is to run the command `:call setreg('a', 'hello register a')` where a is the register a and "hello register a" is the text that you want to store."

Hopefully it makes more sense now! I'll close this :)

**Comment by victorhck** [comment]
looks great! (IMHO) 👍 
Thanks a lot! (time to update spanish translation!)
