### ISSUE TITLE
Useful LSP plugin

### ISSUE THREAD

**Issue by junmoxiao** [iggredible/Learn-Vim#128]
Hello, have you consider add one chapter intro about LSP plugin, such as coc , sometimes they are very useful.
Even neovim now has built-in support for LSP directly.
```
https://github.com/neoclide/coc.nvim
```

**Comment by iggredible** [comment]
Hi @junmoxiao , good suggestion. Right now I am not planning to include LSP plugin because this feature, to my knowledge, is not built-in to Vim (only neovim). 

However, I will let this sit on the back of my mind - maybe I will add a chapter in the future. LSP could be a useful feature that any Vim user might want to learn. I will close this issue. 

Thanks for your input!
