### ISSUE TITLE
Chapter 4 !}column -t -s "|" doesnt work 

### ISSUE THREAD

**Issue by iamchanghao** [iggredible/Learn-Vim#169]
I'm a newbie to Vim, when following the chapters I got stuck at chapter 4 when running the command `!}column -t -s "|"` , my cursor was on "Id"

The error message I got is the following 

```
[No write since last change]
zsh:1: command not found: }column

shell returned 127
```

My whole test file looks like
```
  1 Id|Name|Cuteness
  2 01|Puppy|Very
  3 02|Kitten|Ok
  4 03|Bunny|Ok
  5
```

After googling a bit I found that `:%!column -t -s "|"` works for me, but that's suppose to pipe the whole file to column instead of just a paragraph stated in chapter 4. Am I missing some setting in vimrc? Or something else?

**Comment by yfaimisaka** [comment]
I supposed that you used `:!}column -t -s "|"` instead of `!}` in normal mode under first line. That's a different thing.  Attention that there is no `:` in the command `!}column -t -s "|"`. When you type `!}` under normal mode,  you got `:.,$!` in ex mode, then you can just append `column -t -s "|"` to the `:,$!`,  and it works. More information of the difference between `!` and `:!`, see `:help !` and `help :!`

**Comment by iamchanghao** [comment]
Ah indeed, that is the issue, thank you for the response!
To make sure I understand it, so eventually the command `!}column -t -s "|"` is interpreted as "run `.,.+3!column -t -s "|"`" because
- `!}` means filter this paragraph, thus in our example it becomes `.,.+3`, then run the external command 
- the external command `column -t -s "|"` is run to the above mentioned range.
