### ISSUE TITLE
remove vimrc section in ch02

### ISSUE THREAD

**Issue by victorhck** [iggredible/Learn-Vim#97]
Hello.
At the begining of [chap02](https://github.com/iggredible/Learn-Vim/blob/master/ch02_buffers_windows_tabs.md) it's mentioned a suggestion to add in vimrc file. And it's followed by a small explanation about how to do that.
Don't know if this still it's necesary, maybe this part was written before chap00 was created. Now in that very first chapter there's a small explanation about what vimrc is, so maybe the explanation in cha02 it's not necessary...
What do you think?

_BTW: The spanish translation it's finished (I'm still doing proofreading, etc) and can be found, apart in GitHub repo, also in [GitBook](https://victorhck.gitbook.io/aprende-vim/)_

**Comment by iggredible** [comment]
Good question! It is necessary because for this particular chapter, we need to have `set hidden` (otherwise, many commands in Ch2 won't work without it).

I thought about mentioning it in ch00, but some people skips reading introductory chapters. If I put it in ch21 (vimrc chapter), it'll be too late. So the best way is to put it in the same chapter, ch02.

Great work on Gitbook btw!  👍 

I am actually in the process of putting together a website too. Should be done soon.

**Comment by victorhck** [comment]
ok, then let's keep that explanation in chap02! ;)

I would like to see that website!!
