### ISSUE TITLE
suggestion for section (or something like that)

### ISSUE THREAD

**Issue by victorhck** [iggredible/Learn-Vim#98]
I think that you have not cover about the <leader> key in the guide... (I'm wrong)
Maybe can be added a section or something in some chapter about this setup?

Greetings.

**Comment by iggredible** [comment]
I thought about including Vim Section movement. 

I ended up going against it because they are very specific and have many special cases. I personally thought there are enough navigations in the chapters already to allow the reader to move anywhere quickly.

Good suggestion though, I will give it more thought and I might add it in the future (no promises 😅 )

We'll see!

(I'm assuming you're talking about `:h section`)

**Comment by iggredible** [comment]
Oh haha 😆 !! That makes a lot of sense now. 

It should already be covered in [Ch 21 - Maps](https://github.com/iggredible/Learn-Vim/blob/master/ch21_vimrc.md#maps)!

**Comment by iggredible** [comment]
It's probably underemphasized. I'll add a few more descriptions to emphasize it.

**Comment by iggredible** [comment]
Added some more details. Thanks for bringing it up!

"By the way, what is this "leader" key in <Leader>tn? ... " - in [Ch 21](https://github.com/iggredible/Learn-Vim/blob/master/ch21_vimrc.md#maps)
